meta_product_name: "CommuSub"
meta_title: "Welcome to CommuSub!"
meta_description: "Open your account to the community and get access to all member's accounts."
meta_image: "img-commusub.png" # should exist in `app/assets/images/`
